BINARY      := usbcan
# MCU code
MCU         := F072xB
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32f072x8.ld

DEFINES := -DUSB2_16

include ../makefile.f0
include ../../makefile.stm32
