BINARY      := usbcan
# MCU code
MCU         := F042x6
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32f042x6.ld

include ../makefile.f0
include ../../makefile.stm32
