BINARY		:= float
# MCU code
MCU			:= F303xb
# change this linking script depending on particular MCU model,
LDSCRIPT	:= stm32f303xB.ld
LDLIBS		:= -lm

include ../makefile.f3
include ../../makefile.stm32
