BINARY      := usbcanrelay
# MCU code
MCU         := F072xB
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32f0728.ld

DEFINES := -DUSB2_16 

include ../makefile.f0
include ../../makefile.stm32
