BINARY      := blink
# MCU code
MCU         := G070xx
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32g070xb.ld

include ../makefile.g0
include ../../makefile.stm32

