BINARY      := canonusb
# MCU code
MCU         ?= F103x8
# change this linking script depending on particular MCU model,
LDSCRIPT    ?= stm32f103x8.ld
DEFINES     := -DSTM32F10X_LD

include ../makefile.f1
include ../../makefile.stm32
