# common include for all F0 series
# MCU FAMILY
FAMILY		?= F0
FP_FLAGS	?= -msoft-float -fsingle-precision-constant -mlittle-endian
ASM_FLAGS	?= -mthumb -mcpu=cortex-m0 -march=armv6-m -mtune=cortex-m0
