BINARY      := PL2303
# MCU code
MCU         ?= F072xB
# change this linking script depending on particular MCU model,
LDSCRIPT    ?= stm32f0728.ld

include ../makefile.f0
include ../../makefile.stm32
