BINARY		:= nitrogen
# MCU code
MCU			:= F302xc
# change this linking script depending on particular MCU model,
LDSCRIPT	:= stm32f302xB.ld
DEFINES := -DUSB1_16

include ../makefile.f3
include ../../makefile.stm32
