// Generated by HASHGEN (https://github.com/eddyem/eddys_snippets/tree/master/stringHash4MCU_)
// Licensed by GPLv3
#include <stdint.h>
#include <stddef.h>
#include "hdr.h"

#ifndef WAL
#define WAL __attribute__ ((weak, alias ("__f1")))
#endif

static int __f1(_U_ uint32_t h, _U_ char *a){return 1;}

int fn_abspos(_U_ uint32_t hash,  _U_ char *args) WAL; // "abspos" (3056382221)

int fn_accel(_U_ uint32_t hash,  _U_ char *args) WAL; // "accel" (1490521981)

int fn_adc(_U_ uint32_t hash,  _U_ char *args) WAL; // "adc" (2963026093)

int fn_button(_U_ uint32_t hash,  _U_ char *args) WAL; // "button" (1093508897)

int fn_canerrcodes(_U_ uint32_t hash,  _U_ char *args) WAL; // "canerrcodes" (1736697870)

int fn_canfilter(_U_ uint32_t hash,  _U_ char *args) WAL; // "canfilter" (3964416573)

int fn_canflood(_U_ uint32_t hash,  _U_ char *args) WAL; // "canflood" (1235816779)

int fn_canfloodt(_U_ uint32_t hash,  _U_ char *args) WAL; // "canfloodT" (506574623)

int fn_canid(_U_ uint32_t hash,  _U_ char *args) WAL; // "canid" (2040257924)

int fn_canignore(_U_ uint32_t hash,  _U_ char *args) WAL; // "canignore" (3209755195)

int fn_canincrflood(_U_ uint32_t hash,  _U_ char *args) WAL; // "canincrflood" (3987155959)

int fn_canpause(_U_ uint32_t hash,  _U_ char *args) WAL; // "canpause" (3981532373)

int fn_canreinit(_U_ uint32_t hash,  _U_ char *args) WAL; // "canreinit" (2030075842)

int fn_canresume(_U_ uint32_t hash,  _U_ char *args) WAL; // "canresume" (2051659720)

int fn_cansend(_U_ uint32_t hash,  _U_ char *args) WAL; // "cansend" (237136225)

int fn_canspeed(_U_ uint32_t hash,  _U_ char *args) WAL; // "canspeed" (549265992)

int fn_canstat(_U_ uint32_t hash,  _U_ char *args) WAL; // "canstat" (237384179)

int fn_diagn(_U_ uint32_t hash,  _U_ char *args) WAL; // "diagn" (2334137736)

int fn_dumpcmd(_U_ uint32_t hash,  _U_ char *args) WAL; // "dumpcmd" (1223955823)

int fn_dumpconf(_U_ uint32_t hash,  _U_ char *args) WAL; // "dumpconf" (3271513185)

int fn_dumperr(_U_ uint32_t hash,  _U_ char *args) WAL; // "dumperr" (1223989764)

int fn_dumpmotflags(_U_ uint32_t hash,  _U_ char *args) WAL; // "dumpmotflags" (36159640)

int fn_emstop(_U_ uint32_t hash,  _U_ char *args) WAL; // "emstop" (2965919005)

int fn_eraseflash(_U_ uint32_t hash,  _U_ char *args) WAL; // "eraseflash" (3177247267)

int fn_esw(_U_ uint32_t hash,  _U_ char *args) WAL; // "esw" (2963094612)

int fn_eswreact(_U_ uint32_t hash,  _U_ char *args) WAL; // "eswreact" (1614224995)

int fn_goto(_U_ uint32_t hash,  _U_ char *args) WAL; // "goto" (4286309438)

int fn_gotoz(_U_ uint32_t hash,  _U_ char *args) WAL; // "gotoz" (3178103736)

int fn_gpio(_U_ uint32_t hash,  _U_ char *args) WAL; // "gpio" (4286324660)

int fn_gpioconf(_U_ uint32_t hash,  _U_ char *args) WAL; // "gpioconf" (1309721562)

int fn_maxspeed(_U_ uint32_t hash,  _U_ char *args) WAL; // "maxspeed" (1498078812)

int fn_maxsteps(_U_ uint32_t hash,  _U_ char *args) WAL; // "maxsteps" (1506667002)

int fn_mcut(_U_ uint32_t hash,  _U_ char *args) WAL; // "mcut" (4022718)

int fn_mcuvdd(_U_ uint32_t hash,  _U_ char *args) WAL; // "mcuvdd" (2517587080)

int fn_microsteps(_U_ uint32_t hash,  _U_ char *args) WAL; // "microsteps" (3974395854)

int fn_minspeed(_U_ uint32_t hash,  _U_ char *args) WAL; // "minspeed" (3234848090)

int fn_motflags(_U_ uint32_t hash,  _U_ char *args) WAL; // "motflags" (2153634658)

int fn_motmul(_U_ uint32_t hash,  _U_ char *args) WAL; // "motmul" (1543400099)

int fn_motreinit(_U_ uint32_t hash,  _U_ char *args) WAL; // "motreinit" (199682784)

int fn_ping(_U_ uint32_t hash,  _U_ char *args) WAL; // "ping" (10561715)

int fn_relpos(_U_ uint32_t hash,  _U_ char *args) WAL; // "relpos" (1278646042)

int fn_relslow(_U_ uint32_t hash,  _U_ char *args) WAL; // "relslow" (1742971917)

int fn_reset(_U_ uint32_t hash,  _U_ char *args) WAL; // "reset" (1907803304)

int fn_saveconf(_U_ uint32_t hash,  _U_ char *args) WAL; // "saveconf" (141102426)

int fn_screen(_U_ uint32_t hash,  _U_ char *args) WAL; // "screen" (2100809349)

int fn_speedlimit(_U_ uint32_t hash,  _U_ char *args) WAL; // "speedlimit" (1654184245)

int fn_state(_U_ uint32_t hash,  _U_ char *args) WAL; // "state" (2216628902)

int fn_stop(_U_ uint32_t hash,  _U_ char *args) WAL; // "stop" (17184971)

int fn_time(_U_ uint32_t hash,  _U_ char *args) WAL; // "time" (19148340)

int fn_tmcbus(_U_ uint32_t hash,  _U_ char *args) WAL; // "tmcbus" (1906135955)

int fn_udata(_U_ uint32_t hash,  _U_ char *args) WAL; // "udata" (2736127636)

int fn_usartstatus(_U_ uint32_t hash,  _U_ char *args) WAL; // "usartstatus" (4007098968)

static uint32_t hashf(const char *str){
    uint32_t hash = 5381;
    uint32_t c;
    while((c = (uint32_t)*str++))
        hash = ((hash << 7) + hash) + c;
    return hash;
}

int parsecmd(const char *str){
        char cmd[CMD_MAXLEN + 1];
        if(!str || !*str) return RET_CMDNOTFOUND;
        int i = 0;
        while(*str > '@' && i < CMD_MAXLEN){ cmd[i++] = *str++; }
        cmd[i] = 0;
        if(*str){
            while(*str <= ' ') ++str;
        }
        char *args = (char*) str;
        uint32_t h = hashf(cmd);
        switch(h){

        case CMD_ABSPOS:
            return fn_abspos(h, args);
        break;
        case CMD_ACCEL:
            return fn_accel(h, args);
        break;
        case CMD_ADC:
            return fn_adc(h, args);
        break;
        case CMD_BUTTON:
            return fn_button(h, args);
        break;
        case CMD_CANERRCODES:
            return fn_canerrcodes(h, args);
        break;
        case CMD_CANFILTER:
            return fn_canfilter(h, args);
        break;
        case CMD_CANFLOOD:
            return fn_canflood(h, args);
        break;
        case CMD_CANFLOODT:
            return fn_canfloodt(h, args);
        break;
        case CMD_CANID:
            return fn_canid(h, args);
        break;
        case CMD_CANIGNORE:
            return fn_canignore(h, args);
        break;
        case CMD_CANINCRFLOOD:
            return fn_canincrflood(h, args);
        break;
        case CMD_CANPAUSE:
            return fn_canpause(h, args);
        break;
        case CMD_CANREINIT:
            return fn_canreinit(h, args);
        break;
        case CMD_CANRESUME:
            return fn_canresume(h, args);
        break;
        case CMD_CANSEND:
            return fn_cansend(h, args);
        break;
        case CMD_CANSPEED:
            return fn_canspeed(h, args);
        break;
        case CMD_CANSTAT:
            return fn_canstat(h, args);
        break;
        case CMD_DIAGN:
            return fn_diagn(h, args);
        break;
        case CMD_DUMPCMD:
            return fn_dumpcmd(h, args);
        break;
        case CMD_DUMPCONF:
            return fn_dumpconf(h, args);
        break;
        case CMD_DUMPERR:
            return fn_dumperr(h, args);
        break;
        case CMD_DUMPMOTFLAGS:
            return fn_dumpmotflags(h, args);
        break;
        case CMD_EMSTOP:
            return fn_emstop(h, args);
        break;
        case CMD_ERASEFLASH:
            return fn_eraseflash(h, args);
        break;
        case CMD_ESW:
            return fn_esw(h, args);
        break;
        case CMD_ESWREACT:
            return fn_eswreact(h, args);
        break;
        case CMD_GOTO:
            return fn_goto(h, args);
        break;
        case CMD_GOTOZ:
            return fn_gotoz(h, args);
        break;
        case CMD_GPIO:
            return fn_gpio(h, args);
        break;
        case CMD_GPIOCONF:
            return fn_gpioconf(h, args);
        break;
        case CMD_MAXSPEED:
            return fn_maxspeed(h, args);
        break;
        case CMD_MAXSTEPS:
            return fn_maxsteps(h, args);
        break;
        case CMD_MCUT:
            return fn_mcut(h, args);
        break;
        case CMD_MCUVDD:
            return fn_mcuvdd(h, args);
        break;
        case CMD_MICROSTEPS:
            return fn_microsteps(h, args);
        break;
        case CMD_MINSPEED:
            return fn_minspeed(h, args);
        break;
        case CMD_MOTFLAGS:
            return fn_motflags(h, args);
        break;
        case CMD_MOTMUL:
            return fn_motmul(h, args);
        break;
        case CMD_MOTREINIT:
            return fn_motreinit(h, args);
        break;
        case CMD_PING:
            return fn_ping(h, args);
        break;
        case CMD_RELPOS:
            return fn_relpos(h, args);
        break;
        case CMD_RELSLOW:
            return fn_relslow(h, args);
        break;
        case CMD_RESET:
            return fn_reset(h, args);
        break;
        case CMD_SAVECONF:
            return fn_saveconf(h, args);
        break;
        case CMD_SCREEN:
            return fn_screen(h, args);
        break;
        case CMD_SPEEDLIMIT:
            return fn_speedlimit(h, args);
        break;
        case CMD_STATE:
            return fn_state(h, args);
        break;
        case CMD_STOP:
            return fn_stop(h, args);
        break;
        case CMD_TIME:
            return fn_time(h, args);
        break;
        case CMD_TMCBUS:
            return fn_tmcbus(h, args);
        break;
        case CMD_UDATA:
            return fn_udata(h, args);
        break;
        case CMD_USARTSTATUS:
            return fn_usartstatus(h, args);
        break;
        default: break;
    }
    return RET_CMDNOTFOUND;
}

