BINARY      := steppers
# MCU code
MCU         := F072xB
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32f072B.ld

include ../makefile.f0
include ../../makefile.stm32
