BINARY      := encoders
# MCU code
MCU         ?= F103xB
# change this linking script depending on particular MCU model,
LDSCRIPT    ?= stm32f103xB.ld
DEFINES := -DSTM32F10X_MD

include ../makefile.f1
include ../../makefile.stm32
