BINARY		:= adc
PREFIX=/opt/ARM10/bin/arm-none-eabi
# MCU code
MCU			:= F303xb
# change this linking script depending on particular MCU model,
LDSCRIPT	:= stm32f303xB.ld

include ../makefile.f3
include ../../makefile.stm32
