BINARY      := usbcdc
PREFIX      := /usr/bin/arm-none-eabi
CFLAGS       = -std=c23
# MCU code
MCU         := G431xx
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32g431xb.ld

include ../makefile.g4
include ../../makefile.stm32

