BINARY      := test
# MCU code
MCU         := G0B1xx
# change this linking script depending on particular MCU model,
LDSCRIPT    := stm32g0b1xb.ld

include ../makefile.g0
include ../../makefile.stm32

