BINARY      := fx3u
# MCU code
MCU         ?= F103xC
# change this linking script depending on particular MCU model,
LDSCRIPT    ?= stm32f103xC.ld
DEFINES     := -DSTM32F10X_HD
INC_DIR     := ../inc

include ../makefile.f1
include ../../makefile.stm32
