BINARY		:= multistepper
# MCU code
MCU			:= F303xd
# change this linking script depending on particular MCU model,
LDSCRIPT	:= stm32f303xD.ld
DEFINES := -DUSB2_16
#DEFINES := -DUSB1_16

include ../makefile.f3
include ../../makefile.stm32
